# Generated by Django 5.2 on 2025-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('posterUrl', models.URLField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
