# Generated by Django 5.2 on 2025-05-23 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showtimes', '0002_session_showtimes_s_movie_i_68ab95_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.JSONField(help_text='массив объектов с координатами: [ { "row": 1, "seat": 2 }, ... ]', verbose_name='Выбранные места')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showtimes.session', verbose_name='Сессия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
