# Generated by Django 5.2 on 2025-05-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_rename_name_hall_title'),
        ('movies', '0001_initial'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['movie'], name='showtimes_s_movie_i_68ab95_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['hall'], name='showtimes_s_hall_id_bf16af_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['startTime'], name='showtimes_s_startTi_c7d978_idx'),
        ),
    ]
