# Generated by Django 5.2 on 2025-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('U', 'Пользователь'), ('A', 'Администратор')], default='U', max_length=10),
        ),
    ]
