services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      API_URL: http://127.0.0.1:8000  # ✅ Вот здесь важно!
      WS_URL: ws://127.0.0.1:8000/ws
    depends_on:
      - backend

  db:
    image: postgres:15
    # остальные настройки...
